/*1*/
CREATE DATABASE GESTION;
USE GESTION;
/*2*/
CREATE TABLE OFICINAS (
    OFICINA INT PRIMARY KEY,
    CIUDAD VARCHAR(15) DEFAULT 'Gijon',
    DIRECTOR INT,
    REGION VARCHAR(10),
    OBJETIVOS DECIMAL(10,2),
    VENTAS DECIMAL(10,2)
);

CREATE TABLE COMERCIALES (
    COMERCIAL INT PRIMARY KEY,
    NOMBRE VARCHAR(15),
    EDAD INT,
    OFICINA INT,
    CARGO VARCHAR(10),
    CONTRATO DATETIME,
    DIRECTOR INT,
    CUOTA DECIMAL(10,2),
    VENTAS DECIMAL(10,2),
    
    FOREIGN KEY (OFICINA) REFERENCES OFICINAS(OFICINA)
);

CREATE TABLE CLIENTES (
    CLIENTE INT PRIMARY KEY,
    EMPRESA VARCHAR(20) NOT NULL,
    COMERCIAL INT,
    LIM_CREDITO DECIMAL(10,2),
    
    FOREIGN KEY (COMERCIAL) REFERENCES COMERCIALES(COMERCIAL),
    
    CHECK (LIM_CREDITO >= 0 AND LIM_CREDITO <= 3000)
);

CREATE TABLE PRODUCTOS (
    ID_FABRICA VARCHAR(3),
    PRODUCTO VARCHAR(5) NOT NULL,
    DESCRIPCION VARCHAR(20),
    PRECIO DECIMAL(10,2) NOT NULL,
    EXISTENCIAS INT NOT NULL,
    
    PRIMARY KEY (ID_FABRICA, PRODUCTO)
);

CREATE TABLE PEDIDOS (
    PEDIDO INT PRIMARY KEY,
    FECHA DATETIME,
    CLIENTE INT,
    COMERCIAL INT,
    ID_FABRICA VARCHAR(3),
    PRODUCTO VARCHAR(5) NOT NULL,
    CANTIDAD INT NOT NULL,
    IMPORTE DECIMAL(10,2) NOT NULL,
    
    FOREIGN KEY (CLIENTE) REFERENCES CLIENTES(CLIENTE),
    FOREIGN KEY (COMERCIAL) REFERENCES COMERCIALES(COMERCIAL)
);

/*3*/
RENAME TABLE OFICINAS TO SUCURSALES;

/*4*/
ALTER TABLE COMERCIALES
ADD APELLIDO1 VARCHAR(20),
ADD APELLIDO2 VARCHAR(20);

/*5*/
ALTER TABLE SUCURSALES
MODIFY DIRECTOR VARCHAR(15);

/*6*/
ALTER TABLE COMERCIALES
CHANGE CARGO PUESTO VARCHAR(10);

/*7*/
CREATE TABLE FABRICA (
    COD_FABRICA VARCHAR(3) PRIMARY KEY,
    NOMBRE VARCHAR(30),
    CIUDAD VARCHAR(20)
);

/*9*/
CREATE USER 'fran';

/*10*/
DROP USER 'fran';