CREATE TABLE OFICINAS (
    NUMOFIC INT PRIMARY KEY,
    NOMCEN VARCHAR(30),
    DIRECEN VARCHAR(30)
);
 
CREATE TABLE DEPARTAMENTOS (
    NUMDEP INT PRIMARY KEY,
    NUMOFIC INT NOT NULL,
    DIRECTOR INT NOT NULL,
    TIPODIR CHAR(1),
    PRESUP DECIMAL(6,2),
    DEPDEP INT,
    NOMDEP VARCHAR(30),
    CONSTRAINT FK_DEP_OFIC
        FOREIGN KEY (NUMOFIC) REFERENCES OFICINAS(NUMOFIC),
    CONSTRAINT FK_DEP_DEP
        FOREIGN KEY (DEPDEP) REFERENCES DEPARTAMENTOS(NUMDEP),
    CONSTRAINT CK_TIPODIR
        CHECK (UPPER(TIPODIR) IN ('F','T'))
);
 
CREATE TABLE EMPLEADOS (
    NUMEMP INT PRIMARY KEY,
    NUMDEP INT NOT NULL,
    EXTENSION VARCHAR(5),
    FECHANAC DATE,
    FECHAING DATE,
    SALARIO DECIMAL(8,2),
    COMISION DECIMAL(7,2),
    NUMHIJOS INT,
    NOMEMP VARCHAR(50),
    CONSTRAINT FK_EMP_DEP
        FOREIGN KEY (NUMDEP) REFERENCES DEPARTAMENTOS(NUMDEP)
);
 
 
/*A*/
SELECT NOMCEN FROM OFICINAS
ORDER BY NOMCEN;
 
/*B*/
SELECT NOMEMP FROM EMPLEADOS
WHERE NUMDEP = 121;
 
/*C*/
SELECT NOMEMP, SALARIO FROM EMPLEADOS
WHERE NUMHIJOS > 3
ORDER BY NOMEMP;
 
/*D*/
SELECT COMISION, NUMDEP, NOMEMP FROM EMPLEADOS
WHERE SALARIO < 1900
  AND COMISION IS NOT NULL
ORDER BY NUMDEP ASC, COMISION DESC;
 
/*E*/
SELECT NOMDEP FROM DEPARTAMENTOS
WHERE PRESUP > 10
ORDER BY NOMDEP;
 
/*F*/
SELECT DISTINCT NUMDEP FROM EMPLEADOS
WHERE SALARIO < 1250;
 
/*G*/
SELECT DISTINCT COMISION FROM EMPLEADOS
WHERE NUMDEP = 110
  AND COMISION IS NOT NULL;
 
/*H*/
SELECT NOMEMP, NUMEMP, EXTENSION FROM EMPLEADOS
WHERE NUMDEP = 121
ORDER BY NOMEMP;
 
/*I*/
SELECT SALARIO, NOMEMP FROM EMPLEADOS
WHERE NUMHIJOS = 0
ORDER BY SALARIO DESC, NOMEMP;
 
/*J*/
SELECT NOMEMP, SALARIO * 14 AS SUELDO_ANUAL FROM EMPLEADOS
WHERE NUMDEP = 100
ORDER BY SUELDO_ANUAL DESC;
 
/*K*/
SELECT SALARIO FROM EMPLEADOS
WHERE COMISION IS NOT NULL
  AND COMISION >= SALARIO * 0.10
ORDER BY SALARIO;
 
/*L*/
SELECT NOMEMP, SALARIO,
       (NUMHIJOS - 2) * 100 AS PAGA_EXTRA,
       SALARIO + (NUMHIJOS - 2) * 100 AS SALARIO_TOTAL
FROM EMPLEADOS
WHERE NUMHIJOS >= 3
ORDER BY NOMEMP;
 
/*M*/
SELECT NOMEMP FROM EMPLEADOS
WHERE NUMHIJOS * 100 <= SALARIO / 10
ORDER BY NOMEMP;
 
/*N*/
SELECT NOMEMP, SALARIO + IFNULL(COMISION, 0) AS SALARIO_TOTAL FROM EMPLEADOS
WHERE NUMDEP = 112
ORDER BY SALARIO_TOTAL DESC, NOMEMP;
 
/*O*/
SELECT NUMEMP, NOMEMP, SALARIO + IFNULL(COMISION,0) AS SALARIO_TOTAL FROM EMPLEADOS
WHERE SALARIO + IFNULL(COMISION,0) > 2300
ORDER BY NUMEMP;
 
/*P*/
SELECT DISTINCT NUMDEP FROM EMPLEADOS
WHERE COMISION IS NOT NULL
  AND COMISION > SALARIO * 0.10;
 
/*Q*/
SELECT NOMEMP FROM EMPLEADOS
WHERE SALARIO BETWEEN 2000 AND 2500
ORDER BY NOMEMP;
 
/*R*/
SELECT NOMEMP FROM EMPLEADOS
WHERE NOMEMP LIKE 'Al%'
ORDER BY NOMEMP;
 
/*S*/
SELECT NOMEMP FROM EMPLEADOS
WHERE SUBSTRING_INDEX(NOMEMP, ', ', -1) LIKE 'L%'
ORDER BY NOMEMP;
 
/*T*/
SELECT NOMEMP FROM EMPLEADOS
WHERE LENGTH(SUBSTRING_INDEX(NOMEMP, ' ', 1)) = 7
ORDER BY NOMEMP;
 
/*U*/
SELECT NOMEMP FROM EMPLEADOS
WHERE LENGTH(SUBSTRING_INDEX(NOMEMP, ' ', 1)) >= 6
   OR LENGTH(SUBSTRING_INDEX(SUBSTRING_INDEX(NOMEMP, ' ', 2), ' ', -1)) >= 6
ORDER BY NOMEMP;
 
/*V*/
SELECT NOMEMP FROM EMPLEADOS
WHERE LENGTH(SUBSTRING_INDEX(SUBSTRING_INDEX(NOMEMP, ', ', 1), ' ', -1)) <= 4
ORDER BY NOMEMP;
 
/*W*/
SELECT NOMEMP FROM EMPLEADOS
WHERE SUBSTRING_INDEX(NOMEMP, ', ', -1) LIKE '%o'
ORDER BY NOMEMP;
 
/*X*/
SELECT NOMEMP, SALARIO, FECHAING FROM EMPLEADOS
WHERE FECHAING > '1988-01-01'
   OR SALARIO < 1500
ORDER BY FECHAING, NOMEMP;
 
/*Y*/
SELECT NOMDEP FROM DEPARTAMENTOS
WHERE NOMDEP NOT LIKE 'DIRECCION%'
  AND NOMDEP NOT LIKE 'SECTOR%'
ORDER BY NOMDEP;