CREATE TABLE OFICINAS (
    NUMOFIC INT PRIMARY KEY,
    NOMCEN VARCHAR(30),
    DIRECEN VARCHAR(30)
);
 
CREATE TABLE DEPARTAMENTOS (
    NUMDEP INT PRIMARY KEY,
    NUMOFIC INT NOT NULL,
    DIRECTOR INT NOT NULL,
    TIPODIR CHAR(1),
    PRESUP DECIMAL(6,2),
    DEPDEP INT,
    NOMDEP VARCHAR(30),
    CONSTRAINT FK_DEP_OFIC
        FOREIGN KEY (NUMOFIC) REFERENCES OFICINAS(NUMOFIC),
    CONSTRAINT FK_DEP_DEP
        FOREIGN KEY (DEPDEP) REFERENCES DEPARTAMENTOS(NUMDEP),
    CONSTRAINT CK_TIPODIR
        CHECK (UPPER(TIPODIR) IN ('F','T'))
);
 
CREATE TABLE EMPLEADOS (
    NUMEMP INT PRIMARY KEY,
    NUMDEP INT NOT NULL,
    EXTENSION VARCHAR(5),
    FECHANAC DATE,
    FECHAING DATE,
    SALARIO DECIMAL(8,2),
    COMISION DECIMAL(7,2),
    NUMHIJOS INT,
    NOMEMP VARCHAR(50),
    CONSTRAINT FK_EMP_DEP
        FOREIGN KEY (NUMDEP) REFERENCES DEPARTAMENTOS(NUMDEP)
);

/*2*/
SELECT NUMDEP,
SUBSTRING(NOMDEP,13,5) AS cinco_siguientes
FROM DEPARTAMENTOS
WHERE LENGTH(NOMDEP) > 12
ORDER BY NUMDEP;

/*4*/
SELECT RIGHT(NOMDEP,3) AS ultimos_tres
FROM DEPARTAMENTOS
ORDER BY NOMDEP;

/*8*/
SELECT COUNT(*) AS empleados_2000
FROM EMPLEADOS
WHERE YEAR(FECHAING) = 2000;