CREATE TABLE SECCIONES (
  ID_SECCION INTEGER PRIMARY KEY,
  NOMBRE_SECCION TEXT NOT NULL UNIQUE
);

CREATE TABLE EMPLEADOS (
  ID_EMPLEADO INTEGER PRIMARY KEY,
  NOMBRE TEXT,
  APELLIDOS TEXT,
  DNI TEXT UNIQUE,
  F_NAC DATE,
  DIRECCION TEXT,
  CIUDAD TEXT,
  PROVINCIA TEXT,
  CP TEXT,
  TELEFONO TEXT,
  EMAIL TEXT,
  PUESTO TEXT,
  F_CONTRATACION DATE,
  NSS TEXT UNIQUE,
  ID_SECCION INTEGER,
  CONSTRAINT FK_SECCION FOREIGN KEY (ID_SECCION) REFERENCES SECCIONES(ID_SECCION)
);
